let express=require('express')
let router=express.Router()
let registerModle=require('../../model/register')
let auth=require('../../middleware/auth')
let {addToCart,cartItem,removeItemFromCart,updateItemFromCart}=require('../addToCartController/addToCartController')
router.post('/addToCart',auth(registerModle),addToCart)
router.get('/cartItem',auth(registerModle),cartItem)
router.post('/removeItemFromCart',auth(registerModle),removeItemFromCart)
router.post('/updateItemFromCart',auth(registerModle),updateItemFromCart)
module.exports=router